################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3CircularBuffer.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileAccessProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileCellManagement.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileClientProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileClientService.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileDataNetworkProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileMockupProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileNetworkProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileNetworkRegistry.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileSMSProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileServerProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileServerService.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileVoiceProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3SMSService.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1AccessProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1BandManagement.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1BaseProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1CellManagement.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1ClientProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1DataNetworkProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1DirectModemProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1ModemCore.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1ModemVerification.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1MultiClientProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1MultiServerProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1PinManagement.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1SMSProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1ScanNetworks.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1ServerProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1VoiceProvider.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3SoftSerial.cpp \
/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3VoiceCallService.cpp 

LINK_OBJ += \
./libraries/GSM/src/GSM3CircularBuffer.cpp.o \
./libraries/GSM/src/GSM3MobileAccessProvider.cpp.o \
./libraries/GSM/src/GSM3MobileCellManagement.cpp.o \
./libraries/GSM/src/GSM3MobileClientProvider.cpp.o \
./libraries/GSM/src/GSM3MobileClientService.cpp.o \
./libraries/GSM/src/GSM3MobileDataNetworkProvider.cpp.o \
./libraries/GSM/src/GSM3MobileMockupProvider.cpp.o \
./libraries/GSM/src/GSM3MobileNetworkProvider.cpp.o \
./libraries/GSM/src/GSM3MobileNetworkRegistry.cpp.o \
./libraries/GSM/src/GSM3MobileSMSProvider.cpp.o \
./libraries/GSM/src/GSM3MobileServerProvider.cpp.o \
./libraries/GSM/src/GSM3MobileServerService.cpp.o \
./libraries/GSM/src/GSM3MobileVoiceProvider.cpp.o \
./libraries/GSM/src/GSM3SMSService.cpp.o \
./libraries/GSM/src/GSM3ShieldV1.cpp.o \
./libraries/GSM/src/GSM3ShieldV1AccessProvider.cpp.o \
./libraries/GSM/src/GSM3ShieldV1BandManagement.cpp.o \
./libraries/GSM/src/GSM3ShieldV1BaseProvider.cpp.o \
./libraries/GSM/src/GSM3ShieldV1CellManagement.cpp.o \
./libraries/GSM/src/GSM3ShieldV1ClientProvider.cpp.o \
./libraries/GSM/src/GSM3ShieldV1DataNetworkProvider.cpp.o \
./libraries/GSM/src/GSM3ShieldV1DirectModemProvider.cpp.o \
./libraries/GSM/src/GSM3ShieldV1ModemCore.cpp.o \
./libraries/GSM/src/GSM3ShieldV1ModemVerification.cpp.o \
./libraries/GSM/src/GSM3ShieldV1MultiClientProvider.cpp.o \
./libraries/GSM/src/GSM3ShieldV1MultiServerProvider.cpp.o \
./libraries/GSM/src/GSM3ShieldV1PinManagement.cpp.o \
./libraries/GSM/src/GSM3ShieldV1SMSProvider.cpp.o \
./libraries/GSM/src/GSM3ShieldV1ScanNetworks.cpp.o \
./libraries/GSM/src/GSM3ShieldV1ServerProvider.cpp.o \
./libraries/GSM/src/GSM3ShieldV1VoiceProvider.cpp.o \
./libraries/GSM/src/GSM3SoftSerial.cpp.o \
./libraries/GSM/src/GSM3VoiceCallService.cpp.o 

CPP_DEPS += \
./libraries/GSM/src/GSM3CircularBuffer.cpp.d \
./libraries/GSM/src/GSM3MobileAccessProvider.cpp.d \
./libraries/GSM/src/GSM3MobileCellManagement.cpp.d \
./libraries/GSM/src/GSM3MobileClientProvider.cpp.d \
./libraries/GSM/src/GSM3MobileClientService.cpp.d \
./libraries/GSM/src/GSM3MobileDataNetworkProvider.cpp.d \
./libraries/GSM/src/GSM3MobileMockupProvider.cpp.d \
./libraries/GSM/src/GSM3MobileNetworkProvider.cpp.d \
./libraries/GSM/src/GSM3MobileNetworkRegistry.cpp.d \
./libraries/GSM/src/GSM3MobileSMSProvider.cpp.d \
./libraries/GSM/src/GSM3MobileServerProvider.cpp.d \
./libraries/GSM/src/GSM3MobileServerService.cpp.d \
./libraries/GSM/src/GSM3MobileVoiceProvider.cpp.d \
./libraries/GSM/src/GSM3SMSService.cpp.d \
./libraries/GSM/src/GSM3ShieldV1.cpp.d \
./libraries/GSM/src/GSM3ShieldV1AccessProvider.cpp.d \
./libraries/GSM/src/GSM3ShieldV1BandManagement.cpp.d \
./libraries/GSM/src/GSM3ShieldV1BaseProvider.cpp.d \
./libraries/GSM/src/GSM3ShieldV1CellManagement.cpp.d \
./libraries/GSM/src/GSM3ShieldV1ClientProvider.cpp.d \
./libraries/GSM/src/GSM3ShieldV1DataNetworkProvider.cpp.d \
./libraries/GSM/src/GSM3ShieldV1DirectModemProvider.cpp.d \
./libraries/GSM/src/GSM3ShieldV1ModemCore.cpp.d \
./libraries/GSM/src/GSM3ShieldV1ModemVerification.cpp.d \
./libraries/GSM/src/GSM3ShieldV1MultiClientProvider.cpp.d \
./libraries/GSM/src/GSM3ShieldV1MultiServerProvider.cpp.d \
./libraries/GSM/src/GSM3ShieldV1PinManagement.cpp.d \
./libraries/GSM/src/GSM3ShieldV1SMSProvider.cpp.d \
./libraries/GSM/src/GSM3ShieldV1ScanNetworks.cpp.d \
./libraries/GSM/src/GSM3ShieldV1ServerProvider.cpp.d \
./libraries/GSM/src/GSM3ShieldV1VoiceProvider.cpp.d \
./libraries/GSM/src/GSM3SoftSerial.cpp.d \
./libraries/GSM/src/GSM3VoiceCallService.cpp.d 


# Each subdirectory must supply rules for building sources it contributes
libraries/GSM/src/GSM3CircularBuffer.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3CircularBuffer.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3MobileAccessProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileAccessProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3MobileCellManagement.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileCellManagement.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3MobileClientProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileClientProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3MobileClientService.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileClientService.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3MobileDataNetworkProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileDataNetworkProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3MobileMockupProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileMockupProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3MobileNetworkProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileNetworkProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3MobileNetworkRegistry.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileNetworkRegistry.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3MobileSMSProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileSMSProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3MobileServerProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileServerProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3MobileServerService.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileServerService.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3MobileVoiceProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3MobileVoiceProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3SMSService.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3SMSService.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1AccessProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1AccessProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1BandManagement.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1BandManagement.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1BaseProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1BaseProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1CellManagement.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1CellManagement.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1ClientProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1ClientProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1DataNetworkProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1DataNetworkProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1DirectModemProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1DirectModemProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1ModemCore.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1ModemCore.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1ModemVerification.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1ModemVerification.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1MultiClientProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1MultiClientProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1MultiServerProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1MultiServerProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1PinManagement.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1PinManagement.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1SMSProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1SMSProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1ScanNetworks.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1ScanNetworks.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1ServerProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1ServerProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3ShieldV1VoiceProvider.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3ShieldV1VoiceProvider.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3SoftSerial.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3SoftSerial.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries/GSM/src/GSM3VoiceCallService.cpp.o: /home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src/GSM3VoiceCallService.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR     -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/cores/arduino" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/variants/standard" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/IRremote/3.4.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/HID/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/TFT/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Ethernet/2.0.0/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/GSM/1.0.6/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Mouse/1.0.1/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Stepper/1.1.3/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/LiquidCrystal/1.0.7/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Servo/1.1.8/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SoftwareSerial/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Firmata/2.5.8/utility" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/CapacitiveSensor/0.5.1" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/Keyboard/1.0.2/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/EEPROM/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/SD/1.2.4/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/packages/arduino/hardware/avr/1.8.3/libraries/SPI/src" -I"/home/dustin/.apps/Sloeber/arduinoPlugin/libraries/WiFi/1.2.7/src" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<"   -o "$@"
	@echo 'Finished building: $<'
	@echo ' '


